### ISSUE TITLE
ModuleNotFoundError: No module named 'pulp.solvers'

### ISSUE THREAD

**Issue by banianzr** [Orange-OpenSource/pyDcop#31]
Hi, I was getting started according to the [tutorial](https://pydcop.readthedocs.io/en/latest/tutorials/getting_started.html) and came across this problem:
`Traceback (most recent call last):
  File "/home/chenchun/anaconda3/envs/pydcopenv/bin/dcop_cli.py", line 54, in <module>
    from pydcop.commands import generate
  File "/home/chenchun/anaconda3/envs/pydcopenv/lib/python3.6/site-packages/pydcop/commands/generate.py", line 96, in <module>
    from pydcop.commands.generators.iot import generate_iot
  File "/home/chenchun/anaconda3/envs/pydcopenv/lib/python3.6/site-packages/pydcop/commands/generators/iot.py", line 49, in <module>
    from pulp.solvers import GLPK_CMD
ModuleNotFoundError: No module named 'pulp.solvers'`

I ran `help(pulp)` and there seemed no submodule named `solvers`.
`...

PACKAGE CONTENTS
    apis (package)
    constants
    pulp
    solverdir (package)
    sparse
    tests (package)
    utilities

SUBMODULES
    choco_api
    coin_api
    const
    core
    cplex_api
    glpk_api
    gurobi_api
    mipcl_api
    mosek_api
    scip_api
    xpress_api

FUNCTIONS
    clock = process_time(...)
        process_time() -> float

...`

Can anyone help me on this problem? Thanks a lot in advance!

**Comment by PierreRustOrange** [comment]
There seems to be a change in pulp's API, thanks for reporting the issue, I'll look into it.

**Comment by Jean-BaptisteLy** [comment]
I create the file solvers.py in lib/python3.7/site-packages/pulp thanks to https://raw.githubusercontent.com/openstack-archive/deb-python-pulp/master/src/pulp/solvers.py 

It works !

**Comment by banianzr** [comment]
> There seems to be a change in pulp's API, thanks for reporting the issue, I'll look into it.

Yes, it seems that pulp 2.0 works, but pulp 2.3 does not work.
