### ISSUE TITLE
Getting an error for graph coloring 

### ISSUE THREAD

**Issue by Ayush-A97** [Orange-OpenSource/pyDcop#7]
Sir,
When I run the very first graph coloring code given in the documentation, I get this error:
File "/home/ubuntu/pyDcop-master/pydcop/algorithms/__init__.py", line 114
    name: str
        ^
SyntaxError: invalid syntax

**Comment by Ayush-A97** [comment]
Thank you sir, that worked : )

**Comment by PierreRustOrange** [comment]
Great :)
